name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    container:
      image: golang:1.25.1-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install make (if missing)
        run: apk add --no-cache make
 
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v1.61.0
      - name: Run CI pipeline
        run: make ci